### ISSUE TITLE
user-can-view-their-entries.md

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/code-journal#4]
## 💰 Motivation

Once a user records some journal entries, they'll want to see them.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframe

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-view-their-entries.png)

## ✅ Task List

- [ ] Add a sibling `div[data-view="entries"]` to the HTML.
- [ ] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [ ] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [ ] Check that the entries list looks good on both mobile and desktop screens.
- [ ] Define a function that takes a single journal `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [ ] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [ ] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [ ] Add a navigation item to the navbar for Entries.
- [ ] Add an anchor to the entries view that shows the entry form.
- [ ] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [ ] Ensure that submitting a new journal entry automatically shows the `'entries'` view.
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
